app:
  security:
    jwt:
      secret-key: ${APPLICATION_SECURITY_JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: ${APPLICATION_SECURITY_JWT_EXPIRATION:86400000} # a day

spring:
  application:
    name: e-learning-platform

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:15432/e-learning-platform}
    username: ${SPRING_DATASOURCE_USERNAME:killreal777}
    password: ${SPRING_DATASOURCE_PASSWORD:qwerty12345}

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

server:
  port: ${SERVER_PORT:8080}