app:

spring:
  application:
    name: e-learning-platform
  main:
    allow-circular-references: true

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:15432/e-learning-platform}
    username: ${SPRING_DATASOURCE_USERNAME:killreal777}
    password: ${SPRING_DATASOURCE_PASSWORD:qwerty12345}


springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

logging:
  structured:
    format:
      file: ecs
  file:
    name: jira-service-log.json
  level:
    root: info


server:
  port: ${SERVER_PORT:8081}